using UnityEngine;

/// <summary>
/// ^Μu]t参
/// </summary>
public class RecycleMarble : MonoBehaviour
{
    /// <summary>
    /// ^Μ杭u]计q
    /// </summary>
    public static int recycleMarbles;

    public GameManager gm;

    private void OnTriggerEnter(Collider other)
    {
        if (other.name.Contains("u]"))
        {
            other.gameObject.GetComponent<Rigidbody>().velocity = Vector3.zero;
            other.transform.position = new Vector3(0, 0, 100);

            // ^Μu]计q W[
            recycleMarbles++;
            // pG ^Μ计q 单 iog程ju]计q ち传 寄よ^X
            if (recycleMarbles == ControlSystem.shootMarbles) gm.SwitchTurn(false);
        }
    }
}
